/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TambahRouteImport } from './routes/tambah'
import { Route as Space_adminRouteImport } from './routes/space_admin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportRouteImport } from './routes/report'
import { Route as Rating_ulasanRouteImport } from './routes/rating_ulasan'
import { Route as Promo_userRouteImport } from './routes/promo_user'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as Payment_userRouteImport } from './routes/payment_user'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as Booking_userRouteImport } from './routes/booking_user'
import { Route as Booking_adminRouteImport } from './routes/booking_admin'
import { Route as BerandaRouteImport } from './routes/beranda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditIdRouteImport } from './routes/edit.$id'

const TambahRoute = TambahRouteImport.update({
  id: '/tambah',
  path: '/tambah',
  getParentRoute: () => rootRouteImport,
} as any)
const Space_adminRoute = Space_adminRouteImport.update({
  id: '/space_admin',
  path: '/space_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const Rating_ulasanRoute = Rating_ulasanRouteImport.update({
  id: '/rating_ulasan',
  path: '/rating_ulasan',
  getParentRoute: () => rootRouteImport,
} as any)
const Promo_userRoute = Promo_userRouteImport.update({
  id: '/promo_user',
  path: '/promo_user',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const Payment_userRoute = Payment_userRouteImport.update({
  id: '/payment_user',
  path: '/payment_user',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const Booking_userRoute = Booking_userRouteImport.update({
  id: '/booking_user',
  path: '/booking_user',
  getParentRoute: () => rootRouteImport,
} as any)
const Booking_adminRoute = Booking_adminRouteImport.update({
  id: '/booking_admin',
  path: '/booking_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BerandaRoute = BerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIdRoute = EditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beranda': typeof BerandaRoute
  '/booking_admin': typeof Booking_adminRoute
  '/booking_user': typeof Booking_userRoute
  '/customer': typeof CustomerRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payment_user': typeof Payment_userRoute
  '/promo': typeof PromoRoute
  '/promo_user': typeof Promo_userRoute
  '/rating_ulasan': typeof Rating_ulasanRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/space_admin': typeof Space_adminRoute
  '/tambah': typeof TambahRoute
  '/edit/$id': typeof EditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beranda': typeof BerandaRoute
  '/booking_admin': typeof Booking_adminRoute
  '/booking_user': typeof Booking_userRoute
  '/customer': typeof CustomerRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payment_user': typeof Payment_userRoute
  '/promo': typeof PromoRoute
  '/promo_user': typeof Promo_userRoute
  '/rating_ulasan': typeof Rating_ulasanRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/space_admin': typeof Space_adminRoute
  '/tambah': typeof TambahRoute
  '/edit/$id': typeof EditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beranda': typeof BerandaRoute
  '/booking_admin': typeof Booking_adminRoute
  '/booking_user': typeof Booking_userRoute
  '/customer': typeof CustomerRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payment_user': typeof Payment_userRoute
  '/promo': typeof PromoRoute
  '/promo_user': typeof Promo_userRoute
  '/rating_ulasan': typeof Rating_ulasanRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/space_admin': typeof Space_adminRoute
  '/tambah': typeof TambahRoute
  '/edit/$id': typeof EditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beranda'
    | '/booking_admin'
    | '/booking_user'
    | '/customer'
    | '/dashboard'
    | '/login'
    | '/payment_user'
    | '/promo'
    | '/promo_user'
    | '/rating_ulasan'
    | '/report'
    | '/settings'
    | '/space_admin'
    | '/tambah'
    | '/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beranda'
    | '/booking_admin'
    | '/booking_user'
    | '/customer'
    | '/dashboard'
    | '/login'
    | '/payment_user'
    | '/promo'
    | '/promo_user'
    | '/rating_ulasan'
    | '/report'
    | '/settings'
    | '/space_admin'
    | '/tambah'
    | '/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/beranda'
    | '/booking_admin'
    | '/booking_user'
    | '/customer'
    | '/dashboard'
    | '/login'
    | '/payment_user'
    | '/promo'
    | '/promo_user'
    | '/rating_ulasan'
    | '/report'
    | '/settings'
    | '/space_admin'
    | '/tambah'
    | '/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BerandaRoute: typeof BerandaRoute
  Booking_adminRoute: typeof Booking_adminRoute
  Booking_userRoute: typeof Booking_userRoute
  CustomerRoute: typeof CustomerRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  Payment_userRoute: typeof Payment_userRoute
  PromoRoute: typeof PromoRoute
  Promo_userRoute: typeof Promo_userRoute
  Rating_ulasanRoute: typeof Rating_ulasanRoute
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRoute
  Space_adminRoute: typeof Space_adminRoute
  TambahRoute: typeof TambahRoute
  EditIdRoute: typeof EditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tambah': {
      id: '/tambah'
      path: '/tambah'
      fullPath: '/tambah'
      preLoaderRoute: typeof TambahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space_admin': {
      id: '/space_admin'
      path: '/space_admin'
      fullPath: '/space_admin'
      preLoaderRoute: typeof Space_adminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating_ulasan': {
      id: '/rating_ulasan'
      path: '/rating_ulasan'
      fullPath: '/rating_ulasan'
      preLoaderRoute: typeof Rating_ulasanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo_user': {
      id: '/promo_user'
      path: '/promo_user'
      fullPath: '/promo_user'
      preLoaderRoute: typeof Promo_userRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment_user': {
      id: '/payment_user'
      path: '/payment_user'
      fullPath: '/payment_user'
      preLoaderRoute: typeof Payment_userRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking_user': {
      id: '/booking_user'
      path: '/booking_user'
      fullPath: '/booking_user'
      preLoaderRoute: typeof Booking_userRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking_admin': {
      id: '/booking_admin'
      path: '/booking_admin'
      fullPath: '/booking_admin'
      preLoaderRoute: typeof Booking_adminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beranda': {
      id: '/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof BerandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof EditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BerandaRoute: BerandaRoute,
  Booking_adminRoute: Booking_adminRoute,
  Booking_userRoute: Booking_userRoute,
  CustomerRoute: CustomerRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  Payment_userRoute: Payment_userRoute,
  PromoRoute: PromoRoute,
  Promo_userRoute: Promo_userRoute,
  Rating_ulasanRoute: Rating_ulasanRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRoute,
  Space_adminRoute: Space_adminRoute,
  TambahRoute: TambahRoute,
  EditIdRoute: EditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
