/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TambahRouteImport } from './routes/tambah'
import { Route as Space_adminRouteImport } from './routes/space_admin'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EditRouteImport } from './routes/edit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as Booking_adminRouteImport } from './routes/booking_admin'
import { Route as BerandaRouteImport } from './routes/beranda'

const TambahRoute = TambahRouteImport.update({
  id: '/tambah',
  path: '/tambah',
  getParentRoute: () => rootRouteImport,
} as any)
const Space_adminRoute = Space_adminRouteImport.update({
  id: '/space_admin',
  path: '/space_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Booking_adminRoute = Booking_adminRouteImport.update({
  id: '/booking_admin',
  path: '/booking_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BerandaRoute = BerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/beranda': typeof BerandaRoute
  '/booking_admin': typeof Booking_adminRoute
  '/dashboard': typeof DashboardRoute
  '/edit': typeof EditRoute
  '/login': typeof LoginRoute
  '/promo': typeof PromoRoute
  '/space_admin': typeof Space_adminRoute
  '/tambah': typeof TambahRoute
}
export interface FileRoutesByTo {
  '/beranda': typeof BerandaRoute
  '/booking_admin': typeof Booking_adminRoute
  '/dashboard': typeof DashboardRoute
  '/edit': typeof EditRoute
  '/login': typeof LoginRoute
  '/promo': typeof PromoRoute
  '/space_admin': typeof Space_adminRoute
  '/tambah': typeof TambahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/beranda': typeof BerandaRoute
  '/booking_admin': typeof Booking_adminRoute
  '/dashboard': typeof DashboardRoute
  '/edit': typeof EditRoute
  '/login': typeof LoginRoute
  '/promo': typeof PromoRoute
  '/space_admin': typeof Space_adminRoute
  '/tambah': typeof TambahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/beranda'
    | '/booking_admin'
    | '/dashboard'
    | '/edit'
    | '/login'
    | '/promo'
    | '/space_admin'
    | '/tambah'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/beranda'
    | '/booking_admin'
    | '/dashboard'
    | '/edit'
    | '/login'
    | '/promo'
    | '/space_admin'
    | '/tambah'
  id:
    | '__root__'
    | '/beranda'
    | '/booking_admin'
    | '/dashboard'
    | '/edit'
    | '/login'
    | '/promo'
    | '/space_admin'
    | '/tambah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BerandaRoute: typeof BerandaRoute
  Booking_adminRoute: typeof Booking_adminRoute
  DashboardRoute: typeof DashboardRoute
  EditRoute: typeof EditRoute
  LoginRoute: typeof LoginRoute
  PromoRoute: typeof PromoRoute
  Space_adminRoute: typeof Space_adminRoute
  TambahRoute: typeof TambahRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tambah': {
      id: '/tambah'
      path: '/tambah'
      fullPath: '/tambah'
      preLoaderRoute: typeof TambahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space_admin': {
      id: '/space_admin'
      path: '/space_admin'
      fullPath: '/space_admin'
      preLoaderRoute: typeof Space_adminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking_admin': {
      id: '/booking_admin'
      path: '/booking_admin'
      fullPath: '/booking_admin'
      preLoaderRoute: typeof Booking_adminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beranda': {
      id: '/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof BerandaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  BerandaRoute: BerandaRoute,
  Booking_adminRoute: Booking_adminRoute,
  DashboardRoute: DashboardRoute,
  EditRoute: EditRoute,
  LoginRoute: LoginRoute,
  PromoRoute: PromoRoute,
  Space_adminRoute: Space_adminRoute,
  TambahRoute: TambahRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
